name: Build and Push to ACR

on:
  push:
    branches:
      - main # Trigger on changes to the main branch
  workflow_dispatch: # Also possible to trigger manually

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3

      - name: "Login via Azure CLI"
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Build and push image"
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}
      - run: |
          docker build . -t ${{ secrets.ACR_NAME }}.azurecr.io/service-backend-tester:latest
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/service-backend-tester:latest
